notifications:
  email: false
language: csharp
mono:
  - 5.12.0
solution: B9AnimationModules.sln
env:
  global:
  - PATH="${PATH}:${TRAVIS_BUILD_DIR}/bin"
  - VERSION="$(git describe --tags)"
  - KSP_VERSION="$(cat KSP_VERSION)"
  - KSP_DLL_PATH="/opt/ksp/assembly/KSP_DLLs/${KSP_VERSION}"
  - BUILD_DIR="/var/tmp/b9_animation_modules/build"
install:
  - install-ksp-dlls
  - test -f "${KSP_DLL_PATH}/Assembly-CSharp.dll"
  - nuget restore ${TRAVIS_SOLUTION}
script:
  - msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" ${TRAVIS_SOLUTION}
  - mkdir -pv "${BUILD_DIR}"
  - mkdir -pv "${BUILD_DIR}/assemble"
  - mkdir -pv "${BUILD_DIR}/assemble/B9AnimationModules"
  - mkdir -pv "${BUILD_DIR}/assemble/B9AnimationModules/GameData"
  - mkdir -pv "${BUILD_DIR}/package"
  - cp -r "${TRAVIS_BUILD_DIR}/GameData/B9AnimationModules" "${BUILD_DIR}/assemble/B9AnimationModules/GameData"
  - cp -v "${TRAVIS_BUILD_DIR}/README.md" "${TRAVIS_BUILD_DIR}/LICENSE" "${BUILD_DIR}/assemble/B9AnimationModules/"
  - cp -v "${TRAVIS_BUILD_DIR}/README.md" "${TRAVIS_BUILD_DIR}/LICENSE" "${BUILD_DIR}/assemble/B9AnimationModules/GameData/B9AnimationModules/"
  - (cd "${BUILD_DIR}/assemble/B9AnimationModules" && zip -rv "${BUILD_DIR}/package/B9AnimationModules.zip" .)
after_success:
  - mkdir -pv "${BUILD_DIR}/release"
  - cp -v "${BUILD_DIR}/package/B9AnimationModules.zip" "${BUILD_DIR}/release/B9AnimationModules_${VERSION}.zip"
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_DEPLOY_TOKEN}
    file: ${BUILD_DIR}/release/*.zip
    file_glob: true
    name: "B9AnimationModules ${TRAVIS_TAG} for KSP ${KSP_VERSION}"
    on:
      tags: true
